{{
    config(
        materialized = 'incremental',
        unique_key= 'DATE'
    )
}}

{% set now = modules.datetime.datetime.now() %}

select 
--Key columns    
    COM.DATE,
    COM.DEPOT_CODE,
--Amuse.com details
    --COM.COM_CUSTOMERS,
    COM.COM_DISTINCT_CUSTOMERS,
	COM.COM_DISCOUNTS,
	COM.COM_GROSS_REVENUE,
	COM.COM_GROSS_REVENUE_EX_FEES,
	COM.COM_TAX_TOTAL,
	COM.COM_NET_SALES,
	COM.COM_GROSS_RECEIPT,
	COM.COM_TOTAL_ORDERS_PLACED,
	COM.COM_AVERAGE_ORDER_VALUE, 
	--COM.COM_GROSS_MARGIN,
	COM.COM_CUSTOMER_FIRST_ORDERS,
	COM.COM_CUSTOMER_REPEAT_ORDERS,
--Weedmaps details
    --WM.WM_CUSTOMERS,
    WM.WM_DISTINCT_CUSTOMERS,
	WM.WM_DISCOUNTS,
	WM.WM_GROSS_REVENUE,
	WM.WM_GROSS_REVENUE_EX_FEES,
	WM.WM_TAX_TOTAL,
	WM.WM_NET_SALES,
	WM.WM_GROSS_RECEIPT,
	WM.WM_TOTAL_ORDERS_PLACED,
	WM.WM_AVERAGE_ORDER_VALUE, 
	--WM.WM_GROSS_MARGIN,
	WM.WM_CUSTOMER_FIRST_ORDERS,
	WM.WM_CUSTOMER_REPEAT_ORDERS,
--710Labs-TheList details
    --TL.THE_LIST_CUSTOMERS,
    TL.THE_LIST_DISTINCT_CUSTOMERS,
	TL.THE_LIST_DISCOUNTS,
	TL.THE_LIST_GROSS_REVENUE,
	TL.THE_LIST_GROSS_REVENUE_EX_FEES,
	TL.THE_LIST_TAX_TOTAL,
	TL.THE_LIST_NET_SALES,
	TL.THE_LIST_GROSS_RECEIPT,
	TL.THE_LIST_TOTAL_ORDERS_PLACED,
	TL.THE_LIST_AVERAGE_ORDER_VALUE, 
	--TL.THE_LIST_GROSS_MARGIN,
	TL.THE_LIST_CUSTOMER_FIRST_ORDERS,
	TL.THE_LIST_CUSTOMER_REPEAT_ORDERS,
--710Labs-Concierge details
    --TC.CONCIERGE_CUSTOMERS,
    TC.CONCIERGE_DISTINCT_CUSTOMERS,
	TC.CONCIERGE_DISCOUNTS,
	TC.CONCIERGE_GROSS_REVENUE,
	TC.CONCIERGE_GROSS_REVENUE_EX_FEES,
	TC.CONCIERGE_TAX_TOTAL,
	TC.CONCIERGE_NET_SALES,
	TC.CONCIERGE_GROSS_RECEIPT,
	TC.CONCIERGE_TOTAL_ORDERS_PLACED,
	TC.CONCIERGE_AVERAGE_ORDER_VALUE, 
	--TC.CONCIERGE_GROSS_MARGIN,
	TC.CONCIERGE_CUSTOMER_FIRST_ORDERS,
	TC.CONCIERGE_CUSTOMER_REPEAT_ORDERS,
--Houseplant details
    --HP.HOUSEPLANT_CUSTOMERS,
    HP.HOUSEPLANT_DISTINCT_CUSTOMERS,
	HP.HOUSEPLANT_DISCOUNTS,
	HP.HOUSEPLANT_GROSS_REVENUE,
	HP.HOUSEPLANT_GROSS_REVENUE_EX_FEES,
	HP.HOUSEPLANT_TAX_TOTAL,
	HP.HOUSEPLANT_NET_SALES,
	HP.HOUSEPLANT_GROSS_RECEIPT,
	HP.HOUSEPLANT_TOTAL_ORDERS_PLACED,
	HP.HOUSEPLANT_AVERAGE_ORDER_VALUE, 
	--HP.HOUSEPLANT_GROSS_MARGIN,
	HP.HOUSEPLANT_CUSTOMER_FIRST_ORDERS,
	HP.HOUSEPLANT_CUSTOMER_REPEAT_ORDERS,
--Cohort columns
	MONTH(COM.DATE) as MONTH,
	YEAR(COM.DATE) as YEAR,
	DAYOFWEEK(COM.DATE) as DAY_OF_WEEK,
	DAY(COM.DATE) as DAY,
	QUARTER(COM.DATE) as QUARTER
from {{ref('L1_stg_metrics_COM_data')}} COM 
left join {{ref('L1_stg_metrics_WM_data')}} WM on WM.DATE=COM.DATE
left join {{ref('L1_stg_metrics_List_data')}} TL on TL.DATE=COM.DATE
left join {{ref('L1_stg_metrics_Concierge_data')}} TC on TC.DATE=COM.DATE
left join {{ref('L1_stg_metrics_Houseplant_data')}} HP on HP.DATE=COM.DATE
{% if is_incremental() %}
where 
COM.DATE>(select max(DATE) from DAILY_METRICS)
{% endif %}