
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'etl'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'amuse_snowflake'


# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

on-run-start:
    - "ALTER SESSION SET TIMEZONE = 'UTC';"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  etl:
    
      # Applies to all files under models/example/
      source:
          materialized: ephemeral
      stg:
          transient: false
          materialized: ephemeral
      transform:
          transient: false
          materialized: table

vars:
  depots: 
    - 'lax1'
    - 'sfo1'     
      
  tickets:
    - '"AMUSE_DEV_INGESTION"."INGESTION_TREEZ_LAX1_TICKETS"."TICKETS"'
    - '"AMUSE_DEV_INGESTION"."INGESTION_TREEZ_SFO1_TICKETS"."TICKETS"'

  customers:
    - '"AMUSE_DEV_INGESTION"."INGESTION_TREEZ_LAX1_CUSTOMERS"."CUSTOMERS"'
    - '"AMUSE_DEV_INGESTION"."INGESTION_TREEZ_SFO1_CUSTOMERS"."CUSTOMERS"'

  depot_ids:
    - 'lax1_id'
    - 'sfo1_id'

  products:
    - '"AMUSE_DEV_INGESTION"."INGESTION_TREEZ_LAX1_PRODUCTS"."PRODUCTS"'
    - '"AMUSE_DEV_INGESTION"."INGESTION_TREEZ_SFO1_PRODUCTS"."PRODUCTS"'
  
  storeid:
    - '334'
    - '388'
  
  inventory:
    - '"AMUSE_DEV_INGESTION"."INGESTION"."INGESTION_TREEZ_INVENTORY"'

  invioces:
    - '"AMUSE_DEV_INGESTION"."INGESTION"."INGESTION_TREEZ_INVOICES"'
